### ISSUE TITLE
Fehler bei Bodies

### ISSUE THREAD

**Issue by Selemba1000** [emign/libEmi_Template#12]
```
class TestScene:SceneTemplate() {

    override suspend fun sceneAfterInit() {

    }

    override val viewWillLoad: suspend () -> Unit={
        registerBody(Rectangle(0,0,100,100,fillColor = Colors.GREEN))
    }

    override val viewDidLoad: suspend () -> Unit={

    }

}
```
Bei diesem Code der als MainScene festgelegt wird, kommt auf Windows, wenn das Spielfenster im Hintergrund geöffnet wird, der folgende Fehler ca jeden Frame, bis mann das Spielfenster in den Vordergrund holt.
```
kotlin.UninitializedPropertyAccessException: lateinit property views has not been initialized
	at com.soywiz.korge.input.MouseEvents.getCoroutineContext(MouseEvents.kt:20)
	at me.emig.engineEmi.screenElements.bodies.Rectangle$$special$$inlined$onOver$2.invoke(MouseEvents.kt:309)
	at me.emig.engineEmi.screenElements.bodies.Rectangle$$special$$inlined$onOver$2.invoke(MouseEvents.kt)
	at com.soywiz.korio.async.Signal.invoke(Signal.kt:87)
	at com.soywiz.korge.input.MouseEvents.update(MouseEvents.kt:265)
	at com.soywiz.korge.view.ViewsKt.updateSingleViewWithViews(Views.kt:384)
	at com.soywiz.korge.view.Views.update(Views.kt:232)
	at com.soywiz.korge.view.Views.frameUpdateAndRender-_rozLdE(Views.kt:221)
	at com.soywiz.korge.Korge$prepareViews$21.invoke(Korge.kt:382)
	at com.soywiz.korge.Korge$prepareViews$21.invoke(Korge.kt:34)
	at com.soywiz.korev.EventDispatcher$Mixin.dispatch(EventDispatcher.kt:50)
	at com.soywiz.korgw.GameWindow.dispatchRenderEvent(GameWindow.kt:369)
	at com.soywiz.korgw.GameWindow.frame(GameWindow.kt:194)
	at com.soywiz.korgw.win32.Win32GameWindow$windProc$1.callback(Win32GameWindow.kt:316)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:520)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:551)
	at com.sun.jna.Native.invokeLong(Native Method)
	at com.sun.jna.Function.invoke(Function.java:428)
	at com.sun.jna.Function.invoke(Function.java:361)
	at com.sun.jna.Library$Handler.invoke(Library.java:265)
	at com.sun.proxy.$Proxy2.DispatchMessage(Unknown Source)
	at com.soywiz.korgw.win32.MyUser32$Companion.DispatchMessage(Win32.kt)
	at com.soywiz.korgw.win32.Win32.DispatchMessage(Win32.kt)
	at com.soywiz.korgw.win32.Win32GameWindow.loop(Win32GameWindow.kt:497)
	at com.soywiz.korge.Korge.KoruiWithLogger(Korge.kt:412)
	at com.soywiz.korge.Korge.invoke(Korge.kt:476)
	at me.emig.engineEmi.Engine.start(Engine.kt:52)
	at MainKt.main(Main.kt:39)
	at MainKt$$$main.invoke(Unknown Source)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:199)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:114)
	at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
	at MainKt.main(Main.kt)
```

**Comment by emign** [comment]
Bitte in 0.70 erneut testen. Achtung: Geänderte Syntax
